In [3]:
import pandas as pd

df = pd.read_csv("../data/raw/Sample - Superstore.csv", encoding="latin1")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df.shape

(9994, 21)

## Tamaño del Dataset

El conjunto de datos está compuesto por:

- 9.994 registros (filas).
- 21 variables (columnas).

Este volumen de información es suficiente para realizar análisis significativos sobre el rendimiento comercial, el comportamiento de los clientes y la rentabilidad de los productos.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [6]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [13]:
int(df.duplicated().sum())

0

In [9]:
df["Category"].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [10]:
df["Sub-Category"].value_counts()

Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [11]:
df["Region"].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [12]:
df["Segment"].value_counts()

Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

# 1. Comprensión Inicial del Dataset

El dataset Superstore contiene 9.994 registros y 21 variables relacionadas con ventas, clientes, productos y regiones.

Tras una primera exploración, se observa que no existen valores nulos en ninguna de las columnas, lo que facilita el proceso de limpieza y preparación de datos.

Además, el conjunto de datos incluye información sobre ventas, beneficios, descuentos, cantidades vendidas, clientes y ubicaciones geográficas, lo que lo convierte en una fuente adecuada para realizar análisis de negocio y desarrollar un dashboard interactivo en Power BI.

## Principales hallazgos iniciales

Tras la exploración inicial del dataset se han identificado las siguientes características:

- El conjunto de datos contiene 9.994 transacciones y 21 variables.
- No existen valores nulos ni registros duplicados.
- La categoría con mayor número de ventas registradas es Office Supplies, seguida de Furniture y Technology.
- El negocio opera en cuatro regiones: West, East, Central y South.
- El segmento de clientes más representado es Consumer, seguido por Corporate y Home Office.
- Existen múltiples subcategorías de productos, siendo Binders, Paper y Furnishings las más frecuentes.

In [14]:
df["Sales"].sum()

np.float64(2297200.8603)

In [15]:
df["Profit"].sum()

np.float64(286397.0217)

In [16]:
df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

In [17]:
df.groupby("Category")["Profit"].sum().sort_values(ascending=False)

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

## Análisis inicial de ventas y beneficios

Las ventas totales del negocio ascienden a 2.297.200 dólares, generando un beneficio total de 286.397 dólares.

Al analizar las categorías principales, se observa que Technology es la categoría con mayores ventas y también la más rentable.

Por otro lado, Furniture presenta un comportamiento interesante: aunque genera un volumen de ventas similar al de Technology, su beneficio es considerablemente inferior. Esto sugiere la existencia de factores que podrían estar afectando negativamente a su rentabilidad y que serán analizados en etapas posteriores del proyecto.

Office Supplies se sitúa como la segunda categoría más rentable a pesar de no ser la que registra el mayor volumen de ventas.

In [18]:
df.groupby("Region")[["Sales","Profit"]].sum().sort_values("Sales", ascending=False)

               Sales       Profit
Region
West     725457.8245  108418.4489
East     678781.2400   91522.7800
Central  501239.8908   39706.3625
South    391721.9050   46749.4303

In [19]:
df.groupby("Segment")[["Sales","Profit"]].sum().sort_values("Sales", ascending=False)

                    Sales       Profit
Segment
Consumer     1.161401e+06  134119.2092
Corporate    7.061464e+05   91979.1340
Home Office  4.296531e+05   60298.6785

## Análisis por región y segmento de clientes

El análisis regional muestra que West es la región con mayor volumen de ventas y beneficio, seguida de East.

Sin embargo, se observa un comportamiento interesante entre las regiones Central y South. Aunque Central registra un mayor volumen de ventas, South genera un beneficio superior, lo que podría indicar una mejor rentabilidad o una estrategia comercial más eficiente.

Respecto a los segmentos de clientes, Consumer representa el grupo más importante para la compañía, concentrando el mayor volumen de ventas y beneficios. Corporate ocupa la segunda posición, mientras que Home Office representa la menor participación dentro del negocio.

In [20]:
import matplotlib.pyplot as plt